- name: Delete the puma config file
  sudo: yes
  command: rm /etc/puma.conf removes=/etc/puma.conf

- name: Create an empty puma config file
  sudo: yes
  command: touch /etc/puma.conf

- name: Create a stub release directory for the public app
  file: state=directory
    path=/data/{{ app_name }}-public/releases/stub
    owner=deploy

- name: Create /data/appname-public/current
  file: state=link
    src=/data/{{ app_name }}-public/releases/stub
    dest=/data/{{ app_name }}-public/current
    force=yes owner=deploy

- name: Add appname-public to puma jungle
  sudo: yes
  command: /etc/init.d/puma add /data/{{ app_name }}-public/current deploy

- name: Create a stub release directory for the admin app
  file: state=directory
    path=/data/{{ app_name }}-admin/releases/stub
    owner=deploy

- name: Create /data/appname-admin/current
  file: state=link
    src=/data/{{ app_name }}-admin/releases/stub
    dest=/data/{{ app_name }}-admin/current
    force=yes owner=deploy

- name: Add appname-admin to puma jungle
  sudo: yes
  command: /etc/init.d/puma add /data/{{ app_name }}-admin/current deploy

