- name: Install Puma gem
  sudo: yes
  command: gem install puma --no-rdoc --no-ri

- name: Copy Puma init.d script
  sudo: yes
  copy: src=puma/puma dest=/etc/init.d/puma force=yes mode=755

- name: Copy Puma runner to an accessible location
  sudo: yes
  copy: src=puma/run-puma dest=/usr/local/bin/run-puma force=yes mode=755
